language: node_js
notifications:
  email: false
sudo: false
before_deploy:
- test $TRAVIS_TEST_RESULT = 0
jobs:
  include:
    - stage: Run npm test
      script:
      # We can skip Travis if there are only changes to files like the CHANGELOG
      - ./bin/check-skip-ci.sh
      # Ensure Travis aborts without running tests if the package-lock.json file needs updating
      - ./bin/check-package-lock.sh
      # TravisCI is slower than our local machines, so results in intermittent timeouts
      # using the `--runInBand` flag we can force it to without requiring as much
      # resources (https://facebook.github.io/jest/docs/en/troubleshooting.html#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server)
      - npm test -- --runInBand
    # Heroku is configured to automatically deploy the following branches
    # once CI passes:
    # master         -> http://govuk-frontend-review.herokuapp.com/
